[build]
  publish = "public/"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-add-instagram"
  [plugins.inputs]
    imageFolder = "src/images/instagram"
    dataFile = "static/instagram.json"
    feedTTL = 30
    imageTTL = 1209600
    imageSize = "m"
    username = "nodeschoolsm"